# Whitelist Config 

Prefix: "&fWhitelist&b+"

whitelist: false
no_whitelisted: "&fWhitelist&b+ &aYou are not important enough to be whitelisted."
whitelisted:
- "santicraft234yt"
- "md_5"

# Messages Config

Messages:
  no-permission: "&4No permission :)"
  whitelist-on: "Whitelist is now &a&lON&f!"
  whitelist-off: "&fWhitelist is now &c&lOFF&f!"
  requiere-name: "&7Please enter a name!"
  Whitelist-Add: "%player% &fAdded of the Whitelist"
  Whitelist-Remove: "%player% &fRemoved of the Whitelist"
  Whitelist-List: "&a&lWhitelisted: &7%players%"

Placeholder_messages:
  enabled: "&2ENABLED"
  disabled: "&4DISABLED"